version: "3"
services:
  test-ruby2.7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-ruby2.7
    command: tail -f /dev/null
    environment:
      - BUNDLE_GEMFILE=Gemfile
  test-ruby2.6:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-ruby2.6
    command: tail -f /dev/null
    environment:
      - BUNDLE_GEMFILE=Gemfile
  test-ruby2.5:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-ruby2.5
    command: tail -f /dev/null
    environment:
      - BUNDLE_GEMFILE=Gemfile
  test-ruby2.4:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-ruby2.4
    command: tail -f /dev/null
    environment:
      - BUNDLE_GEMFILE=Gemfile
  test-ruby2.3:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-ruby2.3
    command: tail -f /dev/null
    environment:
      - BUNDLE_GEMFILE=Gemfile
  test-ruby2.2:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-ruby2.2
    command: tail -f /dev/null
    environment:
      - BUNDLE_GEMFILE=gemfiles/ruby_2.2.gemfile
  test-ruby2.1:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-ruby2.1
    command: tail -f /dev/null
    environment:
      - BUNDLE_GEMFILE=gemfiles/ruby_2.1.gemfile

