
name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler: latest
          bundler-cache: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq build-essential automake autoconf libtool

      - name: Set Credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${GITHUB_TOKEN}\n" > $HOME/.gem/credentials
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish to GitHub Packages
        run: |
          export OWNER=$( echo ${{ github.repository }} | cut -d "/" -f 1 )
          gem build geoip2_c.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
          # gem push *.gem
