name: ubuntu

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.0"
          - "2.7"
          - "2.6"
          - "2.5"
          - "2.4"
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: "x64"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq build-essential automake autoconf libtool
          gem install -N bundler
          bundle install --jobs 4 --retry 3
      - name: Build
        run: bundle exec rake compile
      - name: Run test
        run: bundle exec rake test
