name: windows

on:
  - push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby:
          - "2.6"
          - "2.5"
          - "2.4"
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: "x64"
      - name: Install dependencies
        run: |
          ruby -v
          choco install msys2
          pacman -Syu
          gem install -N bundler
          bundle install --jobs 4 --retry 3
      - name: Build
        run: bundle exec rake compile
      - name: Run test
        run: bundle exec rake test
